name: 'Enforce Rebase'
description: 'Enforce rebasing on master before merging'
inputs:
  default-branch:
    description: 'The branch to enforce rebasing on'
    requred: true
    default: 'master'
runs:
  using: 'node20'
  main: 'index.js'
